const CSRF=document.querySelector('meta[name=csrf_token]').content;let S=null,selected=null,drag=null;
const api=async(path,method='GET',body=null)=>{let o={method,headers:{'X-CSRFToken':CSRF}};if(body!==null){o.headers['Content-Type']='application/json';o.body=JSON.stringify(body)}let r=await fetch('/plugins/tweak_view_ng/'+path,o);let j=await r.json();if(!r.ok)throw Error(j.error||r.statusText);return j};
function msg(t,bad=false){let e=document.getElementById('status');e.textContent=t;e.className=bad?'err':'muted'}
async function refresh(){try{S=await api('api/state');document.getElementById('screen').textContent=`${S.screen.width}×${S.screen.height} • Pwn ${S.pwnagotchi_version}`;renderList();renderEditor();renderProfiles();scale();msg(`undo ${S.history.undo} • redo ${S.history.redo}${S.pending_missing.length?' • pending '+S.pending_missing.join(', '):''}`)}catch(e){msg(e.message,true)}}
function renderList(){if(!S)return;let q=document.getElementById('search').value.toLowerCase(),ul=document.getElementById('elements');ul.innerHTML='';Object.entries(S.elements).filter(([n])=>n.toLowerCase().includes(q)).forEach(([n,e])=>{let li=document.createElement('li');li.className='el'+(n===selected?' sel':'');li.innerHTML=`<b>${esc(n)}</b><span class=type>${esc(e.type)}</span>`;li.onclick=()=>{selected=n;renderList();renderEditor();drawBoxes()};ul.appendChild(li)})}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function renderEditor(){let ed=document.getElementById('editor'),t=document.getElementById('title');ed.innerHTML='';if(!S||!selected||!S.elements[selected]){t.textContent='Select an element';return}let e=S.elements[selected];t.textContent=selected+' · '+e.type;e.editable.forEach(k=>{let v=e.properties[k],row=document.createElement('div');row.className='row';let label=document.createElement('label');label.textContent=k;let input;if(['font','text_font','label_font','alt_font'].includes(k)){input=document.createElement('select');S.fonts.forEach(f=>{let o=document.createElement('option');o.value=f;o.textContent=f;if(f===v)o.selected=true;input.appendChild(o)})}else if(k==='wrap'){input=document.createElement('input');input.type='checkbox';input.checked=!!v}else{input=document.createElement('input');input.value=Array.isArray(v)?v.join(','):v??'';if(k==='xy')input.dataset.xy='1'}input.id='p_'+k;row.append(label,input);ed.appendChild(row)})}
function readProps(){let e=S.elements[selected],p={};e.editable.forEach(k=>{let i=document.getElementById('p_'+k);if(!i)return;p[k]=k==='wrap'?i.checked:i.value});return p}
async function apply(){if(!selected)return;try{await api('api/update','POST',{element:selected,properties:readProps()});await refresh();reloadPreview();msg('applied ✓')}catch(e){msg(e.message,true)}}
async function revertEl(){if(!selected)return;try{await api('api/revert','POST',{element:selected});await refresh();reloadPreview();msg('reverted ✓')}catch(e){msg(e.message,true)}}
async function resetAll(){if(!confirm('Reset the active profile?'))return;try{await api('api/reset','POST',{});await refresh();reloadPreview()}catch(e){msg(e.message,true)}}
async function undo(){try{await api('api/undo','POST',{});await refresh();reloadPreview()}catch(e){msg(e.message,true)}}async function redo(){try{await api('api/redo','POST',{});await refresh();reloadPreview()}catch(e){msg(e.message,true)}}
function addShape(type){let name=prompt('Shape name');if(!name)return;api('api/add_shape','POST',{name,type,properties:{xy:[5,5,40,25],color:255,width:1}}).then(()=>{selected=name;refresh();reloadPreview()}).catch(e=>msg(e.message,true))}
function renderProfiles(){let s=document.getElementById('profile');s.innerHTML='';S.profiles.forEach(n=>{let o=document.createElement('option');o.value=n;o.textContent=n;o.selected=n===S.active_profile;s.appendChild(o)});s.onchange=()=>api('api/profile','POST',{name:s.value}).then(()=>{selected=null;refresh();reloadPreview()}).catch(e=>msg(e.message,true))}
function newProfile(){let n=prompt('New profile name');if(!n)return;api('api/profile','POST',{name:n}).then(()=>{selected=null;refresh();reloadPreview()}).catch(e=>msg(e.message,true))}
async function exportCfg(){let d=await api('api/export');let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(d,null,2)],{type:'application/json'}));a.download='tweak_view_ng.json';a.click();URL.revokeObjectURL(a.href)}
function importCfg(inp){let f=inp.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{let d=JSON.parse(r.result);api('api/import','POST',d).then(()=>{selected=null;refresh();reloadPreview()}).catch(e=>msg(e.message,true))}catch(e){msg('invalid JSON',true)}};r.readAsText(f)}
function reloadPreview(){let im=document.getElementById('preview');im.src='/ui?t='+Date.now()}
function scale(){if(!S)return;let im=document.getElementById('preview'),frame=document.getElementById('frame'),maxW=Math.max(250,document.querySelector('.stage').clientWidth-40),maxH=Math.max(150,document.querySelector('.stage').clientHeight-40),sc=Math.min(maxW/S.screen.width,maxH/S.screen.height,4);if(window.innerWidth<850)sc=Math.min((window.innerWidth-38)/S.screen.width,3);sc=Math.max(.5,sc);frame.style.width=(S.screen.width*sc)+'px';frame.style.height=(S.screen.height*sc)+'px';im.style.width='100%';im.style.height='100%';drawBoxes()}
function drawBoxes(){let ov=document.getElementById('overlay');ov.innerHTML='';if(!S)return;Object.entries(S.elements).forEach(([n,e])=>{let xy=e.properties.xy;if(!xy)return;if(!Array.isArray(xy))xy=String(xy).split(',').map(Number);let x=xy[0]||0,y=xy[1]||0,w=xy.length>=4?Math.max(4,(xy[2]-x)):18,h=xy.length>=4?Math.max(4,(xy[3]-y)):12;let b=document.createElement('div');b.className='box'+(n===selected?' sel':'');b.style.left=(x/S.screen.width*100)+'%';b.style.top=(y/S.screen.height*100)+'%';b.style.width=(w/S.screen.width*100)+'%';b.style.height=(h/S.screen.height*100)+'%';b.title=n;b.onpointerdown=ev=>startDrag(ev,n,xy);b.onclick=()=>{selected=n;renderList();renderEditor();drawBoxes()};ov.appendChild(b)})}
function startDrag(ev,n,xy){selected=n;renderList();renderEditor();let frame=document.getElementById('frame').getBoundingClientRect();drag={id:ev.pointerId,n,xy:[...xy],sx:ev.clientX,sy:ev.clientY,fw:frame.width,fh:frame.height};ev.target.setPointerCapture(ev.pointerId);ev.target.onpointermove=moveDrag;ev.target.onpointerup=endDrag}
function moveDrag(ev){if(!drag)return;let dx=Math.round((ev.clientX-drag.sx)*S.screen.width/drag.fw),dy=Math.round((ev.clientY-drag.sy)*S.screen.height/drag.fh),a=[...drag.xy];a[0]+=dx;a[1]+=dy;if(a.length>=4){a[2]+=dx;a[3]+=dy}let i=document.getElementById('p_xy');if(i)i.value=a.join(',')}
function endDrag(ev){if(!drag)return;drag=null;apply()}
window.addEventListener('resize',scale);document.getElementById('preview').onload=()=>{scale();drawBoxes()};refresh();setInterval(()=>reloadPreview(),7000);
